# frontend/Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# Copier uniquement package.json pour installer les dépendances
COPY package*.json ./
RUN npm install

# Ne PAS copier le reste, le volume dans docker-compose prendra le code source

# Exposer le port du serveur React dev
EXPOSE 3000

# Lancer le serveur de développement avec hot-reload
CMD ["npm", "start"]
