server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Sert les fichiers statiques (CSS, JS, images, vidéos)
    location / {
        try_files $uri /index.html;
    }

    # Assets
    location /assets/ {
        try_files $uri =404;
    }

    # Images
    location /images/ {
        try_files $uri =404;
    }

    # Videos
    location /videos/ {
        try_files $uri =404;
    }

    error_page 404 /index.html;
}
