server {
    listen 80;
    server_name e-learning-by-ilyas.com www.e-learning-by-ilyas.com;

    root /usr/share/nginx/html;
    index index.html;

    # Let's Encrypt ACME challenge
    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
    }

    # Frontend React
    location / {
        try_files $uri /index.html;
    }

    # Backend FastAPI
    location /api/ {
        proxy_pass http://fastapi_app:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Fichiers statiques
    location /assets/ { try_files $uri =404; }
    location /images/ { try_files $uri =404; }
    location /videos/ { try_files $uri =404; }

    # Page 404 React
    error_page 404 /index.html;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name e-learning-by-ilyas.com www.e-learning-by-ilyas.com;

    ssl_certificate /etc/letsencrypt/live/e-learning-by-ilyas.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/e-learning-by-ilyas.com/privkey.pem;

    location / {
        proxy_pass http://react_app:3000; # Remplacez par le bon service ou port
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://fastapi_app:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
    }

    location /assets/ { try_files $uri =404; }
    location /images/ { try_files $uri =404; }
    location /videos/ { try_files $uri =404; }

    error_page 404 /index.html;
}