# backend-fastapi/Dockerfile.dev
FROM python:3.12-slim

WORKDIR /app

# Installer dépendances système utiles
RUN apt-get update && apt-get install -y curl netcat-openbsd && rm -rf /var/lib/apt/lists/*

# Copier requirements
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code backend
COPY . .

# Exposer le port FastAPI
EXPOSE 8001

# Script pour attendre MySQL
COPY ./wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Lancer FastAPI en dev avec rechargement automatique
CMD /wait-for-it.sh db 3306 -- uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
